
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Demo of Python failure reports with pytest &#8212; pytest documentation</title>
    <link rel="stylesheet" href="../_static/basic.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <script type="text/javascript" src="../_static/language_data.js"></script>
    <link rel="shortcut icon" href="../_static/pytest1favi.ico"/>
    <link rel="search" title="Search" href="../search.html" />
    <link rel="next" title="Basic patterns and examples" href="simple.html" />
    <link rel="prev" title="Examples and customization tricks" href="index.html" />
  </head><body>


    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="simple.html" title="Basic patterns and examples"
             accesskey="N">next</a></li>
        <li class="right" >
          <a href="index.html" title="Examples and customization tricks"
             accesskey="P">previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="../contents.html">pytest-3.10</a> &#187;</li>
          <li class="nav-item nav-item-1"><a href="index.html" accesskey="U">Examples and customization tricks</a> &#187;</li>
      </ul>
    </div>

    <div class="document">
      <div class="documentwrapper">
          <div class="body" role="main">

  <div class="section" id="demo-of-python-failure-reports-with-pytest">
<span id="tbreportdemo"></span><h1>Demo of Python failure reports with pytest<a class="headerlink" href="#demo-of-python-failure-reports-with-pytest" title="Permalink to this headline">Â¶</a></h1>
<p>Here is a nice run of several tens of failures
and how <code class="docutils literal notranslate"><span class="pre">pytest</span></code> presents things (unfortunately
not showing the nice colors here in the HTML that you
get on the terminal - we are working on that):</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span>assertion $ pytest failure_demo.py
=========================== test session starts ============================
platform linux -- Python 3.x.y, pytest-3.x.y, py-1.x.y, pluggy-0.x.y
rootdir: $REGENDOC_TMPDIR/assertion, inifile:
collected 42 items

failure_demo.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF           [100%]

================================= FAILURES =================================
____________________________ test_generative[0] ____________________________

param1 = 3, param2 = 6

    def test_generative(param1, param2):
&gt;       assert param1 * 2 &lt; param2
E       assert (3 * 2) &lt; 6

failure_demo.py:20: AssertionError
_________________________ TestFailing.test_simple __________________________

self = &lt;failure_demo.TestFailing object at 0xdeadbeef&gt;

    def test_simple(self):
        def f():
            return 42

        def g():
            return 43

&gt;       assert f() == g()
E       assert 42 == 43
E        +  where 42 = &lt;function TestFailing.test_simple.&lt;locals&gt;.f at 0xdeadbeef&gt;()
E        +  and   43 = &lt;function TestFailing.test_simple.&lt;locals&gt;.g at 0xdeadbeef&gt;()

failure_demo.py:36: AssertionError
____________________ TestFailing.test_simple_multiline _____________________

self = &lt;failure_demo.TestFailing object at 0xdeadbeef&gt;

    def test_simple_multiline(self):
&gt;       otherfunc_multi(42, 6 * 9)

failure_demo.py:39:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = 42, b = 54

    def otherfunc_multi(a, b):
&gt;       assert a == b
E       assert 42 == 54

failure_demo.py:16: AssertionError
___________________________ TestFailing.test_not ___________________________

self = &lt;failure_demo.TestFailing object at 0xdeadbeef&gt;

    def test_not(self):
        def f():
            return 42

&gt;       assert not f()
E       assert not 42
E        +  where 42 = &lt;function TestFailing.test_not.&lt;locals&gt;.f at 0xdeadbeef&gt;()

failure_demo.py:45: AssertionError
_________________ TestSpecialisedExplanations.test_eq_text _________________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_text(self):
&gt;       assert &quot;spam&quot; == &quot;eggs&quot;
E       AssertionError: assert &#39;spam&#39; == &#39;eggs&#39;
E         - spam
E         + eggs

failure_demo.py:50: AssertionError
_____________ TestSpecialisedExplanations.test_eq_similar_text _____________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_similar_text(self):
&gt;       assert &quot;foo 1 bar&quot; == &quot;foo 2 bar&quot;
E       AssertionError: assert &#39;foo 1 bar&#39; == &#39;foo 2 bar&#39;
E         - foo 1 bar
E         ?     ^
E         + foo 2 bar
E         ?     ^

failure_demo.py:53: AssertionError
____________ TestSpecialisedExplanations.test_eq_multiline_text ____________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_multiline_text(self):
&gt;       assert &quot;foo\nspam\nbar&quot; == &quot;foo\neggs\nbar&quot;
E       AssertionError: assert &#39;foo\nspam\nbar&#39; == &#39;foo\neggs\nbar&#39;
E           foo
E         - spam
E         + eggs
E           bar

failure_demo.py:56: AssertionError
______________ TestSpecialisedExplanations.test_eq_long_text _______________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_long_text(self):
        a = &quot;1&quot; * 100 + &quot;a&quot; + &quot;2&quot; * 100
        b = &quot;1&quot; * 100 + &quot;b&quot; + &quot;2&quot; * 100
&gt;       assert a == b
E       AssertionError: assert &#39;111111111111...2222222222222&#39; == &#39;1111111111111...2222222222222&#39;
E         Skipping 90 identical leading characters in diff, use -v to show
E         Skipping 91 identical trailing characters in diff, use -v to show
E         - 1111111111a222222222
E         ?           ^
E         + 1111111111b222222222
E         ?           ^

failure_demo.py:61: AssertionError
_________ TestSpecialisedExplanations.test_eq_long_text_multiline __________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_long_text_multiline(self):
        a = &quot;1\n&quot; * 100 + &quot;a&quot; + &quot;2\n&quot; * 100
        b = &quot;1\n&quot; * 100 + &quot;b&quot; + &quot;2\n&quot; * 100
&gt;       assert a == b
E       AssertionError: assert &#39;1\n1\n1\n1\n...n2\n2\n2\n2\n&#39; == &#39;1\n1\n1\n1\n1...n2\n2\n2\n2\n&#39;
E         Skipping 190 identical leading characters in diff, use -v to show
E         Skipping 191 identical trailing characters in diff, use -v to show
E           1
E           1
E           1
E           1
E           1...
E
E         ...Full output truncated (7 lines hidden), use &#39;-vv&#39; to show

failure_demo.py:66: AssertionError
_________________ TestSpecialisedExplanations.test_eq_list _________________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_list(self):
&gt;       assert [0, 1, 2] == [0, 1, 3]
E       assert [0, 1, 2] == [0, 1, 3]
E         At index 2 diff: 2 != 3
E         Use -v to get the full diff

failure_demo.py:69: AssertionError
______________ TestSpecialisedExplanations.test_eq_list_long _______________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_list_long(self):
        a = [0] * 100 + [1] + [3] * 100
        b = [0] * 100 + [2] + [3] * 100
&gt;       assert a == b
E       assert [0, 0, 0, 0, 0, 0, ...] == [0, 0, 0, 0, 0, 0, ...]
E         At index 100 diff: 1 != 2
E         Use -v to get the full diff

failure_demo.py:74: AssertionError
_________________ TestSpecialisedExplanations.test_eq_dict _________________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_dict(self):
&gt;       assert {&quot;a&quot;: 0, &quot;b&quot;: 1, &quot;c&quot;: 0} == {&quot;a&quot;: 0, &quot;b&quot;: 2, &quot;d&quot;: 0}
E       AssertionError: assert {&#39;a&#39;: 0, &#39;b&#39;: 1, &#39;c&#39;: 0} == {&#39;a&#39;: 0, &#39;b&#39;: 2, &#39;d&#39;: 0}
E         Omitting 1 identical items, use -vv to show
E         Differing items:
E         {&#39;b&#39;: 1} != {&#39;b&#39;: 2}
E         Left contains more items:
E         {&#39;c&#39;: 0}
E         Right contains more items:
E         {&#39;d&#39;: 0}...
E
E         ...Full output truncated (2 lines hidden), use &#39;-vv&#39; to show

failure_demo.py:77: AssertionError
_________________ TestSpecialisedExplanations.test_eq_set __________________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_set(self):
&gt;       assert {0, 10, 11, 12} == {0, 20, 21}
E       AssertionError: assert {0, 10, 11, 12} == {0, 20, 21}
E         Extra items in the left set:
E         10
E         11
E         12
E         Extra items in the right set:
E         20
E         21...
E
E         ...Full output truncated (2 lines hidden), use &#39;-vv&#39; to show

failure_demo.py:80: AssertionError
_____________ TestSpecialisedExplanations.test_eq_longer_list ______________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_eq_longer_list(self):
&gt;       assert [1, 2] == [1, 2, 3]
E       assert [1, 2] == [1, 2, 3]
E         Right contains more items, first extra item: 3
E         Use -v to get the full diff

failure_demo.py:83: AssertionError
_________________ TestSpecialisedExplanations.test_in_list _________________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_in_list(self):
&gt;       assert 1 in [0, 2, 3, 4, 5]
E       assert 1 in [0, 2, 3, 4, 5]

failure_demo.py:86: AssertionError
__________ TestSpecialisedExplanations.test_not_in_text_multiline __________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_not_in_text_multiline(self):
        text = &quot;some multiline\ntext\nwhich\nincludes foo\nand a\ntail&quot;
&gt;       assert &quot;foo&quot; not in text
E       AssertionError: assert &#39;foo&#39; not in &#39;some multiline\ntext\nw...ncludes foo\nand a\ntail&#39;
E         &#39;foo&#39; is contained here:
E           some multiline
E           text
E           which
E           includes foo
E         ?          +++
E           and a...
E
E         ...Full output truncated (2 lines hidden), use &#39;-vv&#39; to show

failure_demo.py:90: AssertionError
___________ TestSpecialisedExplanations.test_not_in_text_single ____________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_not_in_text_single(self):
        text = &quot;single foo line&quot;
&gt;       assert &quot;foo&quot; not in text
E       AssertionError: assert &#39;foo&#39; not in &#39;single foo line&#39;
E         &#39;foo&#39; is contained here:
E           single foo line
E         ?        +++

failure_demo.py:94: AssertionError
_________ TestSpecialisedExplanations.test_not_in_text_single_long _________

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_not_in_text_single_long(self):
        text = &quot;head &quot; * 50 + &quot;foo &quot; + &quot;tail &quot; * 20
&gt;       assert &quot;foo&quot; not in text
E       AssertionError: assert &#39;foo&#39; not in &#39;head head head head hea...ail tail tail tail tail &#39;
E         &#39;foo&#39; is contained here:
E           head head foo tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail
E         ?           +++

failure_demo.py:98: AssertionError
______ TestSpecialisedExplanations.test_not_in_text_single_long_term _______

self = &lt;failure_demo.TestSpecialisedExplanations object at 0xdeadbeef&gt;

    def test_not_in_text_single_long_term(self):
        text = &quot;head &quot; * 50 + &quot;f&quot; * 70 + &quot;tail &quot; * 20
&gt;       assert &quot;f&quot; * 70 not in text
E       AssertionError: assert &#39;fffffffffff...ffffffffffff&#39; not in &#39;head head he...l tail tail &#39;
E         &#39;ffffffffffffffffff...fffffffffffffffffff&#39; is contained here:
E           head head fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffftail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail tail
E         ?           ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

failure_demo.py:102: AssertionError
______________________________ test_attribute ______________________________

    def test_attribute():
        class Foo(object):
            b = 1

        i = Foo()
&gt;       assert i.b == 2
E       assert 1 == 2
E        +  where 1 = &lt;failure_demo.test_attribute.&lt;locals&gt;.Foo object at 0xdeadbeef&gt;.b

failure_demo.py:110: AssertionError
_________________________ test_attribute_instance __________________________

    def test_attribute_instance():
        class Foo(object):
            b = 1

&gt;       assert Foo().b == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = &lt;failure_demo.test_attribute_instance.&lt;locals&gt;.Foo object at 0xdeadbeef&gt;.b
E        +    where &lt;failure_demo.test_attribute_instance.&lt;locals&gt;.Foo object at 0xdeadbeef&gt; = &lt;class &#39;failure_demo.test_attribute_instance.&lt;locals&gt;.Foo&#39;&gt;()

failure_demo.py:117: AssertionError
__________________________ test_attribute_failure __________________________

    def test_attribute_failure():
        class Foo(object):
            def _get_b(self):
                raise Exception(&quot;Failed to get attrib&quot;)

            b = property(_get_b)

        i = Foo()
&gt;       assert i.b == 2

failure_demo.py:128:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;failure_demo.test_attribute_failure.&lt;locals&gt;.Foo object at 0xdeadbeef&gt;

    def _get_b(self):
&gt;       raise Exception(&quot;Failed to get attrib&quot;)
E       Exception: Failed to get attrib

failure_demo.py:123: Exception
_________________________ test_attribute_multiple __________________________

    def test_attribute_multiple():
        class Foo(object):
            b = 1

        class Bar(object):
            b = 2

&gt;       assert Foo().b == Bar().b
E       AssertionError: assert 1 == 2
E        +  where 1 = &lt;failure_demo.test_attribute_multiple.&lt;locals&gt;.Foo object at 0xdeadbeef&gt;.b
E        +    where &lt;failure_demo.test_attribute_multiple.&lt;locals&gt;.Foo object at 0xdeadbeef&gt; = &lt;class &#39;failure_demo.test_attribute_multiple.&lt;locals&gt;.Foo&#39;&gt;()
E        +  and   2 = &lt;failure_demo.test_attribute_multiple.&lt;locals&gt;.Bar object at 0xdeadbeef&gt;.b
E        +    where &lt;failure_demo.test_attribute_multiple.&lt;locals&gt;.Bar object at 0xdeadbeef&gt; = &lt;class &#39;failure_demo.test_attribute_multiple.&lt;locals&gt;.Bar&#39;&gt;()

failure_demo.py:138: AssertionError
__________________________ TestRaises.test_raises __________________________

self = &lt;failure_demo.TestRaises object at 0xdeadbeef&gt;

    def test_raises(self):
        s = &quot;qwe&quot;  # NOQA
&gt;       raises(TypeError, &quot;int(s)&quot;)

failure_demo.py:148:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

&gt;   int(s)
E   ValueError: invalid literal for int() with base 10: &#39;qwe&#39;

&lt;0-codegen $PYTHON_PREFIX/lib/python3.6/site-packages/_pytest/python_api.py:682&gt;:1: ValueError
______________________ TestRaises.test_raises_doesnt _______________________

self = &lt;failure_demo.TestRaises object at 0xdeadbeef&gt;

    def test_raises_doesnt(self):
&gt;       raises(IOError, &quot;int(&#39;3&#39;)&quot;)
E       Failed: DID NOT RAISE &lt;class &#39;OSError&#39;&gt;

failure_demo.py:151: Failed
__________________________ TestRaises.test_raise ___________________________

self = &lt;failure_demo.TestRaises object at 0xdeadbeef&gt;

    def test_raise(self):
&gt;       raise ValueError(&quot;demo error&quot;)
E       ValueError: demo error

failure_demo.py:154: ValueError
________________________ TestRaises.test_tupleerror ________________________

self = &lt;failure_demo.TestRaises object at 0xdeadbeef&gt;

    def test_tupleerror(self):
&gt;       a, b = [1]  # NOQA
E       ValueError: not enough values to unpack (expected 2, got 1)

failure_demo.py:157: ValueError
______ TestRaises.test_reinterpret_fails_with_print_for_the_fun_of_it ______

self = &lt;failure_demo.TestRaises object at 0xdeadbeef&gt;

    def test_reinterpret_fails_with_print_for_the_fun_of_it(self):
        items = [1, 2, 3]
        print(&quot;items is %r&quot; % items)
&gt;       a, b = items.pop()
E       TypeError: &#39;int&#39; object is not iterable

failure_demo.py:162: TypeError
--------------------------- Captured stdout call ---------------------------
items is [1, 2, 3]
________________________ TestRaises.test_some_error ________________________

self = &lt;failure_demo.TestRaises object at 0xdeadbeef&gt;

    def test_some_error(self):
&gt;       if namenotexi:  # NOQA
E       NameError: name &#39;namenotexi&#39; is not defined

failure_demo.py:165: NameError
____________________ test_dynamic_compile_shows_nicely _____________________

    def test_dynamic_compile_shows_nicely():
        import imp
        import sys

        src = &quot;def foo():\n assert 1 == 0\n&quot;
        name = &quot;abc-123&quot;
        module = imp.new_module(name)
        code = _pytest._code.compile(src, name, &quot;exec&quot;)
        six.exec_(code, module.__dict__)
        sys.modules[name] = module
&gt;       module.foo()

failure_demo.py:183:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def foo():
&gt;    assert 1 == 0
E    AssertionError

&lt;2-codegen &#39;abc-123&#39; $REGENDOC_TMPDIR/assertion/failure_demo.py:180&gt;:2: AssertionError
____________________ TestMoreErrors.test_complex_error _____________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_complex_error(self):
        def f():
            return 44

        def g():
            return 43

&gt;       somefunc(f(), g())

failure_demo.py:194:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
failure_demo.py:12: in somefunc
    otherfunc(x, y)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = 44, b = 43

    def otherfunc(a, b):
&gt;       assert a == b
E       assert 44 == 43

failure_demo.py:8: AssertionError
___________________ TestMoreErrors.test_z1_unpack_error ____________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_z1_unpack_error(self):
        items = []
&gt;       a, b = items
E       ValueError: not enough values to unpack (expected 2, got 0)

failure_demo.py:198: ValueError
____________________ TestMoreErrors.test_z2_type_error _____________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_z2_type_error(self):
        items = 3
&gt;       a, b = items
E       TypeError: &#39;int&#39; object is not iterable

failure_demo.py:202: TypeError
______________________ TestMoreErrors.test_startswith ______________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_startswith(self):
        s = &quot;123&quot;
        g = &quot;456&quot;
&gt;       assert s.startswith(g)
E       AssertionError: assert False
E        +  where False = &lt;built-in method startswith of str object at 0xdeadbeef&gt;(&#39;456&#39;)
E        +    where &lt;built-in method startswith of str object at 0xdeadbeef&gt; = &#39;123&#39;.startswith

failure_demo.py:207: AssertionError
__________________ TestMoreErrors.test_startswith_nested ___________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_startswith_nested(self):
        def f():
            return &quot;123&quot;

        def g():
            return &quot;456&quot;

&gt;       assert f().startswith(g())
E       AssertionError: assert False
E        +  where False = &lt;built-in method startswith of str object at 0xdeadbeef&gt;(&#39;456&#39;)
E        +    where &lt;built-in method startswith of str object at 0xdeadbeef&gt; = &#39;123&#39;.startswith
E        +      where &#39;123&#39; = &lt;function TestMoreErrors.test_startswith_nested.&lt;locals&gt;.f at 0xdeadbeef&gt;()
E        +    and   &#39;456&#39; = &lt;function TestMoreErrors.test_startswith_nested.&lt;locals&gt;.g at 0xdeadbeef&gt;()

failure_demo.py:216: AssertionError
_____________________ TestMoreErrors.test_global_func ______________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_global_func(self):
&gt;       assert isinstance(globf(42), float)
E       assert False
E        +  where False = isinstance(43, float)
E        +    where 43 = globf(42)

failure_demo.py:219: AssertionError
_______________________ TestMoreErrors.test_instance _______________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_instance(self):
        self.x = 6 * 7
&gt;       assert self.x != 42
E       assert 42 != 42
E        +  where 42 = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;.x

failure_demo.py:223: AssertionError
_______________________ TestMoreErrors.test_compare ________________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_compare(self):
&gt;       assert globf(10) &lt; 5
E       assert 11 &lt; 5
E        +  where 11 = globf(10)

failure_demo.py:226: AssertionError
_____________________ TestMoreErrors.test_try_finally ______________________

self = &lt;failure_demo.TestMoreErrors object at 0xdeadbeef&gt;

    def test_try_finally(self):
        x = 1
        try:
&gt;           assert x == 0
E           assert 1 == 0

failure_demo.py:231: AssertionError
___________________ TestCustomAssertMsg.test_single_line ___________________

self = &lt;failure_demo.TestCustomAssertMsg object at 0xdeadbeef&gt;

    def test_single_line(self):
        class A(object):
            a = 1

        b = 2
&gt;       assert A.a == b, &quot;A.a appears not to be b&quot;
E       AssertionError: A.a appears not to be b
E       assert 1 == 2
E        +  where 1 = &lt;class &#39;failure_demo.TestCustomAssertMsg.test_single_line.&lt;locals&gt;.A&#39;&gt;.a

failure_demo.py:242: AssertionError
____________________ TestCustomAssertMsg.test_multiline ____________________

self = &lt;failure_demo.TestCustomAssertMsg object at 0xdeadbeef&gt;

    def test_multiline(self):
        class A(object):
            a = 1

        b = 2
&gt;       assert (
            A.a == b
        ), &quot;A.a appears not to be b\nor does not appear to be b\none of those&quot;
E       AssertionError: A.a appears not to be b
E         or does not appear to be b
E         one of those
E       assert 1 == 2
E        +  where 1 = &lt;class &#39;failure_demo.TestCustomAssertMsg.test_multiline.&lt;locals&gt;.A&#39;&gt;.a

failure_demo.py:249: AssertionError
___________________ TestCustomAssertMsg.test_custom_repr ___________________

self = &lt;failure_demo.TestCustomAssertMsg object at 0xdeadbeef&gt;

    def test_custom_repr(self):
        class JSON(object):
            a = 1

            def __repr__(self):
                return &quot;This is JSON\n{\n  &#39;foo&#39;: &#39;bar&#39;\n}&quot;

        a = JSON()
        b = 2
&gt;       assert a.a == b, a
E       AssertionError: This is JSON
E         {
E           &#39;foo&#39;: &#39;bar&#39;
E         }
E       assert 1 == 2
E        +  where 1 = This is JSON\n{\n  &#39;foo&#39;: &#39;bar&#39;\n}.a

failure_demo.py:262: AssertionError
============================= warnings summary =============================
failure_demo.py:25
  $REGENDOC_TMPDIR/assertion/failure_demo.py:25: RemovedInPytest4Warning: Metafunc.addcall is deprecated and scheduled to be removed in pytest 4.0.
  Please use Metafunc.parametrize instead.
    metafunc.addcall(funcargs=dict(param1=3, param2=6))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================== 42 failed, 1 warnings in 0.12 seconds ===================
</pre></div>
</div>
</div>


          </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="simple.html" title="Basic patterns and examples"
             >next</a></li>
        <li class="right" >
          <a href="index.html" title="Examples and customization tricks"
             >previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="../contents.html">pytest-3.10</a> &#187;</li>
          <li class="nav-item nav-item-1"><a href="index.html" >Examples and customization tricks</a> &#187;</li>
      </ul>
    </div>

    <div class="footer" role="contentinfo">
        &#169; Copyright 2015â2018 , holger krekel and pytest-dev team.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.8.5.
    </div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7597274-13']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

  </body>
</html>